### ISSUE TITLE
Frage zu regulären Ausdrücken

### ISSUE THREAD

**Issue by PhilippMatthes** [mkroetzsch/FormaleSysteme#29]
In Vorbereitung auf die Klausur bin ich gerade dabei, alle Übungen durchzugehen. In [Übung 04](https://iccl.inf.tu-dresden.de/w/images/3/39/FS17-uebung-04.pdf) ist mir etwas aufgefallen:

> Geben Sie zu jedem der regulären Ausdrücke ri einen NFA Mi mit L(Mi) = L(ri) an.
>
> a) r1 = (ab)*
> ...
>
> Wenden Sie dabei den kompositionellen Ansatz zur Konstruktion von NFAs aus der Vorlesung
an.

Mir ist aufgefallen, dass mein Tutor für den regulären Ausdruck **(ab)*** einen NFA konstruiert hat, welcher nicht das leere Wort erzeugen kann. Im Internet habe ich gelesen, dass ein regulärer Ausdruck **a*** jedoch auch eine Sprache beschreibt, welche das leere Wort ε enthält. Mein Ansatz für diese Aufgabe ist ein NFA, welcher ε akzeptiert, mit folgender Übergangsfunktion: [Bild auf Imgur](https://i.imgur.com/hIk67Ld.jpg) 

Meine Frage ist: muss der entsprechende NFA das leere Wort akzeptieren oder darf er es nicht?

**Comment by mmarx** [comment]
(ab)* enthaelt das leere Wort, dieses muss dementsprechend auch vom NFA akzeptiert werden. Das Bild zeigt einen Automaten, der (ab)* akzeptiert, der allerdings nicht wie in der Aufgabenstellung gefordert mittels des kompositionellen Ansatzes aus der Vorlesung konsturiert wurde. Dabei entsteht ein Automat, der das leere Wort ueber einen zusaetzlichen Zustand akzeptiert, der gleichzeitig Final- und Startzustand ist und keinerlei Uebergaenge zu anderen Zustaenden besitzt.

**Comment by PhilippMatthes** [comment]
Ich hatte den kompositionellen Ansatz aus der Vorlesung hier nicht angewendet. Mir ging es nur darum, den zur Frage stehenden Sachverhalt zu klären. Vielen Dank für die Antwort, ich lag also richtig mit meiner Annahme.
