### ISSUE TITLE
Vorlesung 6: Unnötiger Zustand im NFA?

### ISSUE THREAD

**Issue by JuKu** [mkroetzsch/FormaleSysteme#38]
Ich bin mir nicht sicher, ob ich selbst nur falsch gedacht habe oder ob es ein Fehler ist.
In der Vorlesung 6 auf Folie 21 ist in meinen Augen ein unnötiger Zustand zu finden (4), wieso wird dieser nicht weggekürzt?

![sl](https://user-images.githubusercontent.com/1138046/35813408-d8f1a990-0a93-11e8-95cd-b1ff3e5ed253.PNG)

Es handelt sich sowieso nicht um einen Endzustand, weshalb dieser gleich zu qf führen sollte.

**Comment by mmarx** [comment]
Die kompositionelle Methode konstruiert zu einem gegebenen regulaeren Ausdruck einen aequivalenten NFA. Aus Automaten fuer Grundfaelle werden dabei schrittweise groessere Automaten fuer kompliziertere (Teil-)Ausdruecke zusammengesetzt. Dabei werden ε-Uebergaenge entfernt, andere Uebergaenge und insbesondere saemtliche Zustaende bleiben jedoch erhalten. Der entstehende NFA ist daher im Allgemeinen nicht minimal.

**Comment by JuKu** [comment]
Vielen Dank!
Aber wird in der Klausur dann ein minimaler Automat gefordert, oder kann man diesen so stehen lassen?

**Comment by mmarx** [comment]
Was genau gefordert wird, haengt von der Formulierung der Aufgabenstellung ab. Wird (nur) ein aequivalenter NFA gefordert, muss dieser nicht minimal sein. Wuerde explizit die kompositionelle Methode verlangt, waere hier fuer »a|ba*« ein minimaler NFA sogar falsch (denn es ensteht ja eben ein nicht-minimaler NFA).
