### ISSUE TITLE
Frage zu Äquivalenzklassen

### ISSUE THREAD

**Issue by tidenhub** [mkroetzsch/FormaleSysteme#39]
Hallo,
ausgehend von Vorlesung 9 sollte es möglich sein, eine DFA M<sub>L</sub> zu konstruieren, sodass die Anzahl der Zustände in M<sub>L</sub> dem Index von ≃ entspricht.

Für das Beispiel in Vorlesung 8 sollte es mir dann möglich sein, eine M<sub>L</sub> mit 4 Zuständen zu zeichnen.
![image](https://user-images.githubusercontent.com/7394024/35963347-b9eeee36-0cb4-11e8-9670-2f24b89cece7.png)

Mein Ansatz wäre folgender, aber da habe ich 5 Zustände.
![dsc_0622](https://user-images.githubusercontent.com/7394024/35963759-0e791be2-0cb6-11e8-9a28-1189ca83b05f.JPG)

Wie würde ein passender M<sub>L</sub> für dieses Beispiel aussehen?

**Comment by mmarx** [comment]
Die Aequivalenzklassen [ab] und [ba] sind gleich, da ja ba ∈ [ab] gilt. Entsprechend ist auch [ba] dann kein neuer Zustand, die a-Kante vom [b]-Zustand aus geht also eigentlich zum Zustand [ab].

**Comment by tidenhub** [comment]
Okay, aber was ist mit den restlichen Übergängen, damit der DFA wieder total wird?
![dsc_0624](https://user-images.githubusercontent.com/7394024/35968338-d310cb32-0cc3-11e8-9e4a-80e100e15de1.JPG)

**Comment by mmarx** [comment]
Die blauen Übergänge gegen alle zu [b], da sowohl ab, bb, aba wie auch abb in [b] liegen.

**Comment by tidenhub** [comment]
Okay, aber dann erzeugt der Automat M<sub>L</sub> nicht mehr die Sprache L!?
z.B. bba könnte man dann mit M<sub>L</sub> erstellen.

**Comment by mmarx** [comment]
Das stimmt. Tatsächlich ist [b] eine weitere Äquivalenzklasse, wir werden das Beispiel korrigieren.

**Comment by mmarx** [comment]
Das Beispiel ist jetzt korrigiert, der Automat bekommt dann einen weiteren Zustand [bb], zu dem genau alle blauen Uebergaenge im Bild oben fuehren.
