### ISSUE TITLE
Fehler in Beispiel zu Nerode Rechtskongruenz

### ISSUE THREAD

**Issue by FlorianPix** [mkroetzsch/FormaleSysteme#44]
In [lecture-08.tex](https://github.com/knowsys/FormaleSysteme/blob/master/Vorlesungen/lecture-08.tex) gibt es einen Fehler im Beispiel L = {a, ab, ba} auf Folie 23.

Die Nerode-Äquivalenzklasse [b]≃L = {b} hat als mögliche Suffixe w = {​ɛ​, a}.
(statt w = a) da nach dem wort {ab} ∈ L auch ɛ​ folgen kann so wie in der Zeile darüber bei der Äquivalenzklasse [a]≃L.

**Comment by mmarx** [comment]
Im Gegensatz zu `a` ist aber `b` nicht Element von `L`, insbesondere gilt _nicht_ `bɛ ∈ L`, wohl aber `aɛ ∈ L` und `abɛ ∈ L`. Da darueberhinaus auch `ba ∈ L`, nicht aber `aba ∈ L` gilt, koennen die Aequivalenzklassen `[b]` und `[ab]` nicht gleich sein, folglich ist fuer die Klasse `[b]` auch nicht relevant, welche moeglichen Suffixe sich fuer `ab` ergeben.

**Comment by FlorianPix** [comment]
Ich wollte damit auch nicht sagen das die 2 Klassen zu einer Äquivalenzklasse zusammenfallen sonder nur das der 2.mögliche Suffix mit angefügt werden sollte zum Verständniss. (Außerdem ist bb ∉ {a, ab, ba}.)

**Comment by mmarx** [comment]
Es ist ja aber gerade _kein_ moegliches Suffix an dieser Stelle: `aw ∈ L` gilt genau dann, wenn `w` entweder `ɛ` oder `b` ist. `bw ∈ L` gilt genau dann, wenn `w = a` ist (aber, weil `b ∈ L` nicht gilt, eben _nicht_, wenn `w = ɛ` ist).

Die Suffixe fuer `ab` sind _nicht_ relevant fuer die Aequivalenzklasse `[b]`, da die beiden Klassen verschieden sind (das Beispiel oben, das das illustriert, habe ich angepasst),.

**Comment by FlorianPix** [comment]
Danke das hat geholfen 👍
