### ISSUE TITLE
Frage zur Vorlesung vom 9. Oktober 2017

### ISSUE THREAD

**Issue by PhilippMatthes** [mkroetzsch/FormaleSysteme#7]
In den [Folien der 1. Vorlesung](https://github.com/mkroetzsch/FormaleSysteme/blob/master/Vorlesungen/lecture-01.tex) steht 

> Für Sprachen L₁, L₂, K über einem gemeinsamen Alphabet Σ gilt: [...] K = K◦ε = ε◦K

**gilt dies auch für K = ∅?**

**Comment by mkroetzsch** [comment]
Achtung, der Ausdruck muss lauten
```K = K◦{ε} = {ε}◦K```
das heißt, wir betrachten nicht das Wort ε, sondern die Sprache {ε}, die genau das eine Wort ε enthält. Per Definition gilt:
```K◦{ε} = { vw | v in K und w in {ε}}```
und weil w hier nur einen Wert haben kann ist das einfach:
```{ vε | v in K}```
Da ```vε=v``` ist, ist diese Menge gleich
```{ v | v in K}```
was wiederum nur eine umständliche Schreibweise für K selbst ist. Alle diese Umformungen gelten auch dann, wenn K leer ist. Die Antwort auf die Frage lautet also "ja" (der Fall für {ε}◦K ist analog).
